backend:
  name: github
  repo: creativiii/sqlite-experiment
  branch: main
  auth_endpoint: "api/auth"
media_folder: "public/images"
public_folder: "/images"
collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the UI
    folder: "_posts/blog" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{title}}"
    extension: md
    format: yaml-frontmatter
    preview_path: posts/{{slug}}
    fields: 
      - { label: "Layout", name: "layout", widget: "hidden", default: "blog" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }